spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: safa
    password: safa
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8090
